\"
.nr PS 14
.nr VS 16
.ps 14
.vs 16
.sp 1
.ce
        
.sp 8
.tl ''PISCES-IIB''
.sp 2
.ce 
Supplementary report
.sp 7
.ce
Mark R. Pinto
.sp 0.5
.ce
Conor S. Rafferty
.sp 0.5
.ce
Hal R. Yeager
.sp 0.5
.ce
Robert W. Dutton
.sp 3
.ce 3
Stanford Electronics Laboratories
Department of Electrical Engineering
Stanford University, Stanford Ca 94305.
.sp 5
.in +4
.ll -4
.ps 12
.vs 14
\(co\ 	Copyright 1985 The Board of Trustees of the Leland 
.br
\ 	Stanford Junior University. All rights reserved.
