#Fri Aug03 2:55am PST 1990
#
#File to run the test batch
#Note: directories that are skipped are ones that have problems.
#They are included here to provide more examples--caveat emptor.
#
MFLAGS= 'P2= /tmp/icl/bin/pisc2'
#
all:
	cd test01; make ${MFLAGS}
	cd test03; make ${MFLAGS}
	cd test04; make ${MFLAGS}
	cd test05; make ${MFLAGS}
	cd test06; make ${MFLAGS}
	cd test07; make ${MFLAGS}
	cd test08; make ${MFLAGS}
	cd test09; make ${MFLAGS}
	cd test10; make ${MFLAGS}
	cd test11; make ${MFLAGS}
	cd test12; make ${MFLAGS}
clean:
	cd test01; make clean
	cd test02; make clean
	cd test03; make clean
	cd test04; make clean
	cd test05; make clean
	cd test06; make clean
	cd test07; make clean
	cd test08; make clean
	cd test09; make clean
	cd test10; make clean
	cd test11; make clean
	cd test12; make clean
	cd test13; make clean
